### ISSUE TITLE
Wrong Map16 numeration on Duplicate Map16 Tile Finder tool

### ISSUE THREAD

**Issue by ShinyNT** [SMWCentral/OnlineTools#3]
Apparently the [Duplicate Map16 Tile Finder](https://www.smwcentral.net/?p=onlinetools&tool=duplicate_map16) tool can't go further than x7F. Currently, all FG pages are numered correctly (presumably because the limit is x7F), but BG pages aren't, as page x80 gets read as x40, x90 as x50, and so on

Here you can see the results of a page x94 check, where it gets read as x54:
![image](https://user-images.githubusercontent.com/36184001/152827310-8e4a7823-d46d-4be0-93c2-4a54ab1edf38.png)

Testing page x7F being read correctly:
![image](https://user-images.githubusercontent.com/36184001/152828193-3a3b0ddc-8a8e-4e75-ad7c-a0a509ee6564.png)
Testing page x82 being read incorrectly:
![image](https://user-images.githubusercontent.com/36184001/152828378-49a0a8f3-f467-4cfe-b2e3-182feee7c47d.png)

edit: forgot to mention all .map16 files were extracted with latest Lunar Magic (3.31)

**Comment by telinc1** [comment]
Looks like I never updated the original code to be compatible with .map16 files from Lunar Magic 2.50+. It actually turns out this wasn't just a cosmetic problem, as tiles from the new FG pages would have their "acts like" settings ignored and cause false positives.

It should be fixed now. Thanks for the report!
